kind: Pod
apiVersion: v1
metadata:
  name: nginx-service-affy
spec:
  affinity:
    nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
       - matchExpressions:
         - key: color
           operator: In
           values:
                   - red        
     preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: label-1
            operator: In
            values:
            - key-1
            - linux 
  containers:
  - name: nginx-service-affy
    image: nginx
    ports:
    - containerPort: 80
